# ADD NEW DATA TO TABLE

INSERT INTO CUSTOMERS
(CUSTOMERKEY,CITY,BIRTHDATE,DISTRICT,GENDER)
VALUES
('MEHMET ÖZAL','ANTALYA','1990-12-21','ALANYA','E')

#SHOW TABLE

SELECT*FROM CUSTOMERS

#UPDATE NATION AND AGE

UPDATE CUSTOMERS
SET NATION='TR',AGE=65

# CALCULATE AGE

SELECT DATEDIFF (YEAR,'1980-12-11',GETDATE())

# UPDATE AGES ACCORDING TO AUTOMATIC CALCULATED AGE

UPDATE CUSTOMERS
SET NATION='TR',AGE=DATEDIFF (YEAR,BIRTHDATE,GETDATE())